config/routes.rb
TwitterApiTry::Application.routes.draw do

  get 'tweets' => 'tweets#index'
  get 'tweets/show' => 'tweets#show', :as => :show_tweets
  resources 'users'

  

end

app/models/service/tweet_search.rb
require 'twitter_shuwei'
module Service
  class TweetSearch

    def self.search params

      TwitterShuwei::TwitterClient.new(
           :consumer_key => CONSUMER_KEY,
           :consumer_secret => CONSUMER_SECRET,
           :token => OAUTH_TOKEN,
           :secret => OAUTH_TOKEN_SECRET
       ).search_tweet(:keyword=>params[:keyword], :count => params[:count])
    end
  end
end

app/models/service/user_fetch.rb
require 'twitter_shuwei'
module Service
  class UserFetch
    def self.fetch_user params
      TwitterShuwei::TwitterClient.new(
          :consumer_key => CONSUMER_KEY,
          :consumer_secret => CONSUMER_SECRET,
          :token => OAUTH_TOKEN,
          :secret => OAUTH_TOKEN_SECRET
      ).show_user(:name=>params[:name])
    end

    def self.find_timeline user
      tweets = TwitterShuwei::TwitterClient.new(
          :consumer_key => CONSUMER_KEY,
          :consumer_secret => CONSUMER_SECRET,
          :token => OAUTH_TOKEN,
          :secret => OAUTH_TOKEN_SECRET
      ).fetch_timeline(:screen_name=>user.screen_name)
      user.tweets = tweets
      return user
    end
  end
end

app/models/tweet.rb
  class Tweet
    attr_accessor :id, :created_at, :text, :user

    def initialize attributes
      attributes.keys.each {|k| instance_variable_set("@#{k}", attributes[k]) if respond_to?(k) }
    end

    def self.find_all params
      Service::TweetSearch.search params
    end
  end

app/models/user.rb
class User
  attr_accessor :id, :screen_name, :name, :location, :description, :profile_image_url, :status, :tweets

  def initialize attributes
    attributes.keys.each {|k| instance_variable_set("@#{k}", attributes[k]) if respond_to?(k) }
  end

  def self.fetch params
    user = Service::UserFetch.fetch_user params
    return user
  end

  def self.timeline_tweets params
    user = fetch(params)
    Service::UserFetch.find_timeline user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ActionController::Base
  def show
    @tweets = Tweet.find_all params
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  def index
    @user = User.fetch params
  end

  def show
    @user = User.timeline_tweets params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterApiTry</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<%= form_tag(show_tweets_url, method: "get") do %>
    <%= label_tag(:keyword, "Keywords:") %>
    <%= text_field_tag(:keyword) %>
    <%= label_tag(:count, "Count:") %>
    <%= text_field_tag(:count) %>
    <%= submit_tag("Search") %>
<% end %>

app/views/tweets/show.html.erb
<h2>Tweets with '<%= params[:keyword] %>'</h2>
<h5>
  <% @tweets.each do |tweet| %>
      <table>
        <tr>
          <td>Text:</td>
          <td><%= tweet.text %></td>
        </tr>
        <tr>
          <td>By:</td>
          <td><%= tweet.user.name %></td>
        </tr>
        <tr>
          <td>Created at:</td>
          <td><%= tweet.created_at %></td>
        </tr>
      </table>
      <br/>
  <% end %>
</h5>

<%= link_to 'Back', tweets_path %>

app/views/users/show.html.erb
<h2><%=@user.name%></h2>
<%= image_tag(@user.profile_image_url, :size => "180x180") %>
<h5>
  <% @user.tweets.each do |tweet| %>
      <table>
        <tr>
          <td>Text:</td>
          <td><%= tweet.text %></td>
        </tr>
        <tr>
          <td>Created at:</td>
          <td><%= tweet.created_at %></td>
        </tr>
      </table>
      <br/>
  <% end %>
</h5>